### ISSUE TITLE
Rhythmbox 3.4 compatibility

### ISSUE THREAD

**Issue by marciosr** [dmo60/lLyrics#60]
When the last update for rhythmbox come, the plugin llyrics stop working.
I'm using updated arch linux.

Here is the terminal output:

(rhythmbox:9378): Rhythmbox-WARNING **: Could not open device /dev/radio0
/usr/lib/rhythmbox/plugins/equalizer/Conf.py:20: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf, Gst
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/equalizer/equalizer.py", line 38, in do_activate
    self.eq = Gst.ElementFactory.make('equalizer-10bands', None)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 217, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 348, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/llyrics/lLyrics.py", line 139, in do_activate
    self.init_menu()
  File "/usr/lib/rhythmbox/plugins/llyrics/lLyrics.py", line 259, in init_menu
    tooltip=_("Display lyrics for the current playing song"))
  File "/usr/lib/rhythmbox/plugins/llyrics/lLyrics_rb3compat.py", line 478, in add_action
    app.add_accelerator(accel, action_type + "." + action_name, None)
TypeError: Argument 3 does not allow None as a value

**Comment by dmo60** [comment]
Thanks for reporting! I will try fix it in the next days or weeks.

**Comment by dmo60** [comment]
Sorry, I probably won't have time for this before November.

**Comment by David-UPCT** [comment]
Good news! Llyrics didn't work for me in Rhythmbox 3.4, but it works perferctly again in 3.4.1. I use archlinux.

**Comment by marciosr** [comment]
Yes it is working for me too! Tks

**Comment by dmo60** [comment]
Ok, thanks for reporting! Since this seems to be fixed, I will close the issue now.
