### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by MzeeAlii** [dmo60/lLyrics#65]
The plugin is activated on the plugins list, but I don't see it on the player views. I've tried installing it using ppa and by compiling the source. Both ways don't seem to work. Starting Rhythmbox from terminal gives this if it make any sense:
`Traceback (most recent call last):
  File "/home/ali/.local/share/rhythmbox/plugins/lLyrics/lLyrics.py", line 138, in do_activate
    self.init_menu()
  File "/home/ali/.local/share/rhythmbox/plugins/lLyrics/lLyrics.py", line 258, in init_menu
    tooltip=_("Display lyrics for the current playing song"))
  File "/home/ali/.local/share/rhythmbox/plugins/lLyrics/lLyrics_rb3compat.py", line 478, in add_action
    app.add_accelerator(accel, action_type + "." + action_name, None)
TypeError: Argument 3 does not allow None as a value`

I'm on v3.4 now, I recall using v3.3 was fine.

**Comment by timoloewe** [comment]
Thanks! Seems like they made changes to the API. I will look into that when I find some time.

**Comment by wim1948** [comment]
Same problen here
regards 
wim

**Comment by timoloewe** [comment]
I'm on Rhythmbox 3.4.1 and the plugin is working fine. Can you give me some information about the OS/distribution you are running?

**Comment by MzeeAlii** [comment]
@dmo60 it works? I'm on 3.4.0.. Where can I get 3.4.1? And oh, I use Mint now. 18.1 to be exact

**Comment by MzeeAlii** [comment]
The ppa repo came with the system seems to be stuck on v3.3. I actually used this link: http://ubuntuhandbook.org/index.php/2016/08/install-rhythmbox-3-4-ubuntu-gnome-16-04/ to install v3.4. I didn't check the source codes to see if v3.4.1 is available. I actually thought that v.3.4 is the latest at the moment.

**Comment by wim1948** [comment]
Hello Timo,

I'am working with Ubuntu 16.04 -64-bits.

Rhythmbox 3.4. installed from the fossfreedom PPA.


The problem exits when I switched fromm 14.04 to 16.04.

I tried reinstalling Rhythmbox, reinstalling the PPA.
Nothing solved the problem.

Hope you can help me.
Regards
Wim

Herewith the output frome the terminal:



wim@PC-kamer:~$ rhythmbox

(rhythmbox:19947): Gtk-WARNING **: Theme directory  of theme oxygen has 
no size field


(rhythmbox:19947): Grilo-WARNING **: [registry] grl-registry.c:640: 
Could not open plugins' info directory 
'/usr/lib/x86_64-linux-gnu/grilo-0.2': Fout bij openen van map 
‘/usr/lib/x86_64-linux-gnu/grilo-0.2’: Bestand of map bestaat niet

(rhythmbox:19947): Rhythmbox-WARNING **: Failed to load Grilo plugins: 
All configured plugin paths are invalid
Rhythmbox: could not connect to socket
Rhythmbox: Bestand of map bestaat niet

(rhythmbox:19947): libdmapsharing-WARNING **: Unable to start music 
sharing server on port 3689: Could not listen on address 0.0.0.0, port 
3689: Fout bij het koppelen aan adres: Adres is al in gebruik. Trying 
any open IPv6 port

(rhythmbox:19947): Gtk-WARNING **: Theme directory  of theme oxygen has 
no size field

Traceback (most recent call last):
   File "/usr/lib/rhythmbox/plugins/replaygain/replaygain.py", line 44, 
in do_activate
     self.player = ReplayGainPlayer(self.object)
   File "/usr/lib/rhythmbox/plugins/replaygain/player.py", line 48, in 
__init__
     if Gst.ElementFactory.find(e) is None:
   File "/usr/lib/python3/dist-packages/gi/overrides/Gst.py", line 347, 
in fake_method
     raise NotInitialized("Please call Gst.init(argv) before using 
GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using 
GStreamer
Traceback (most recent call last):
   File "/home/wim/.local/share/rhythmbox/plugins/lLyrics/lLyrics.py", 
line 138, in do_activate
     self.init_menu()
   File "/home/wim/.local/share/rhythmbox/plugins/lLyrics/lLyrics.py", 
line 258, in init_menu
     tooltip=_("Display lyrics for the current playing song"))
   File 
"/home/wim/.local/share/rhythmbox/plugins/lLyrics/lLyrics_rb3compat.py", 
line 478, in add_action
     app.add_accelerator(accel, action_type + "." + action_name, None)
TypeError: Argument 3 does not allow None as a value

(rhythmbox:19947): Gtk-WARNING **: Theme directory  of theme oxygen has 
no size field






Op 15-02-17 om 22:22 schreef Timo Loewe:
